[package]
name = "wnd_macros"
version = "0.1.0"
edition = "2021"

[features]
todo_attr = []
thread = []

[lib]
proc-macro = true

[dependencies]
quote = "1.0.27"
syn = { version = "1.0.109", features = ["full"] }
